services:
  app:
    container_name: go_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
  db:
    image: postgres
    container_name: go_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: insider_case_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s
  redis:
    image: redis:latest
    container_name: insider_case_redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD:
    command: redis-server --requirepass ""  # Remove password if not set
volumes:
  postgres_data:
